package reserva_vuelos;

public enum EstadoVuelo {
    CHECK_IN_EN_LINEA_DISPONIBLE,
    CHECK_IN_PRESENCIAL_DISPONIBLE,
    EMBARQUE_ABIERTO,
    AVISO_DE_CIERRE_DE_EMBARQUE_CERCANO,
    EMBARQUE_CERRADO,
    VUELO_EN_CURSO,
    VUELO_RETRASADO,
    VUELO_CANCELADO,
}